#!/bin/sh
RS90EU_PATH=$(dirname $(realpath $0))
RS90EU_INS_PATH=$(realpath ~/.rs90ExtraUtils)
OPK_LOOP_DEVICE=$(df "${RS90EU_PATH}" | tail -1 | awk -F ' |/' '{print $3}')
OPK_PATH=$(cat /sys/block/${OPK_LOOP_DEVICE}/loop/backing_file 2>/dev/null)

main() {
	[ -n "${OPK_PATH}" ] || {
		dialog --msgbox "Please run it on st! \n" 0 0
		return 1
	}
	until main_menu
	do
		case "$?" in
		1) install_swclock ;;
		2) remove_swclock ;;
		3) install_chinese ;;
		4) remove_chinese ;;
		5) set_timezone ;;
		6) default_timezone ;;
		7) return 0 ;;
		esac
	done
}

main_menu() {
	local menusel
	dialog --menu rs90ExtraUtils 0 0 0 \
		1 "Install Software Clock" \
		2 "Remove Software Clock" \
		3 "Install Chinese Language File" \
		4 "Remove Chinese Language File" \
		5 "Set Timezone to UTC+8" \
		6 "Default Timezone (UTC)" \
		7 "Exit" 2>/var/tmp/rs90eu_sel
	menusel=$(cat /var/tmp/rs90eu_sel)
	rm -f /var/tmp/rs90eu_sel
	[ -n "menusel" ] && return ${menusel}
	return 0
}

install_swclock() {
	local init_path=/media/data/local/etc/init.d

	{   mkdir -p "${RS90EU_INS_PATH}" ~/".gmenu2x/sections/settings" &&
		echo "params=-m swclock.hide.desktop \"${OPK_PATH}\"" | cat "${RS90EU_PATH}/swclock.gmenu2x" - \
				> ~/".gmenu2x/sections/settings/05_swclock" &&
		dialog --msgbox "Install Software Clock Success! \n" 0 0
	} || {
		dialog --msgbox "Install Software Clock Fail! \n" 0 0
	}
	dialog --yesno "Auto Load/Save Time on Power On/OFF? \n" 0 0 && {
		{   mkdir -p "${RS90EU_INS_PATH}" "${init_path}" &&
			cp "${RS90EU_PATH}/swclock" "${RS90EU_INS_PATH}/swclock" &&
			cp -f "${RS90EU_PATH}/swclock.init" "${init_path}/S05swclock.sh" &&
			dialog --msgbox "Set Auto Load/Save Success! \n" 0 0
		} || {
			dialog --msgbox "Set Auto Load/Save Fail! \n" 0 0
		}
	}
	dialog --yesno "Run Software Clock on Boot? \n" 0 0 && {
		{   echo -ne "#!/bin/sh\nOPK_FILE=${OPK_PATH}\n" | cat - "${RS90EU_PATH}/swclock.autostart" \
					> ~/".autostart" &&
			chmod +x ~/".autostart" &&
			dialog --msgbox "Install Software Clock on Boot Success! \n" 0 0
		} || {
			dialog --msgbox "Install Software Clock on Boot Fail! \n" 0 0
		}
	}

}

remove_swclock_configs() {
	local SDCARD_PATH="$(cat /proc/mounts | grep '^/dev/mmcblk0p1' | awk '{print $2}')"
	local NAND_CONF="${RS90EU_INS_PATH}/Configs/swclock.conf"
	local SDCARD_CONF="${SDCARD_PATH}/.rs90ExtraUtils/swclock.conf"
	local ret=0
	[ ! -e "${NAND_CONF}"   ] || rm -rf "${NAND_CONF}"   || ret=1
	[ ! -e "${SDCARD_CONF}" ] || rm -rf "${SDCARD_CONF}" || ret=1
	return ${ret}
}

remove_swclock() {
	local init_path=/media/data/local/etc/init.d
	{   rm -f ~/".gmenu2x/sections/settings/05_swclock" &&
		rm -f "${RS90EU_INS_PATH}/swclock" &&
		rm -f "${init_path}/S05swclock.sh" &&
		rm -r ~/".autostart" &&
		remove_swclock_configs &&
		dialog --msgbox "Remove Software Clock Success! \n" 0 0
	} || {
		dialog --msgbox "Remove Software Clock Fail! \n" 0 0
	}
}

install_chinese() {
	{   mkdir -p ~/".gmenu2x/translations" &&
		cp "${RS90EU_PATH}/Chinese.lang" ~/".gmenu2x/translations/Chinese" &&
		dialog --msgbox "Install Chinese Language File Success! \n" 0 0
	} || {
		dialog --msgbox "Install Chinese Language File Fail! \n" 0 0
	}
}

remove_chinese() {
	{	rm -f ~/".gmenu2x/translations/Chinese" &&
		rmdir --ignore-fail-on-non-empty ~/".gmenu2x/translations" &&
		dialog --msgbox "Remove Chinese Language File Success! \n" 0 0
	} || {
		dialog --msgbox "Remove Chinese Language File Fail! \n" 0 0
	}
}

set_timezone() {
	{   echo "export TZ=Asia/Shanghai" > ~/.profile &&
		chmod +x ~/.profile &&
		dialog --msgbox "Set Timezone Success! \n" 0 0
	} || {
		dialog --msgbox "Set Timezone Fail! \n" 0 0
	}
}

default_timezone() {
	{   rm -f ~/.profile &&
		dialog --msgbox "Set Default Timezone Success! \n" 0 0
	} || {
		dialog --msgbox "Set Default Timezone Fail! \n" 0 0
	}
}

main "$@"
